name: grandis
description: tdr infomation for desktop embedding.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: '>=1.5.9-pre.270'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  html: ^0.14.0+2
  url_launcher: ^5.1.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansCJKjp
      fonts:
        - asset: fonts/NotoSansCJKjp/NotoSansCJKjp-Thin.otf
          weight: 100
        - asset: fonts/NotoSansCJKjp/NotoSansCJKjp-Light.otf
          weight: 300
        - asset: fonts/NotoSansCJKjp/NotoSansCJKjp-Regular.otf
          weight: 400
        - asset: fonts/NotoSansCJKjp/NotoSansCJKjp-Medium.otf
          weight: 500
        - asset: fonts/NotoSansCJKjp/NotoSansCJKjp-Bold.otf
          weight: 700
        - asset: fonts/NotoSansCJKjp/NotoSansCJKjp-Black.otf
          weight: 900
